# Stage 1: Build
FROM node:22.16.0 as builder

USER node

WORKDIR /home/app/dev

COPY --chown=node:node ./package*.json ./

RUN npm ci

# Stage 2: Runtime
FROM node:22.16.0

WORKDIR /home/app/dev

COPY --from=builder /home/app/dev/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
