services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      # 인증 비활성화 (TLS/SSL)
      - xpack.security.enabled=false
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - server
  fluentd:
    build:
      context: ./
      dockerfile: Dockerfile-efk.test
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - '24224:24224'
    depends_on:
      # elasticsearch 서비스가 정상적으로 구동된 후 health check
      elasticsearch:
        condition: service_healthy
    restart: always
    networks:
      - server
  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always
    networks:
      - server
networks:
  server:
    driver: bridge
